pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        master: master
        feature: .+
    github:
      credentials:
        description: GitHub Secret Text Access Token
    jenkins:
      workflows:
        branch: "v0.1.0"
    slack:
      channel: 'git-notifications'
  branches:
    master:
      steps:
        - github:
          - createRelease:
