pipelines:
  general:
    debug: true
  tools:
    branches:
      patterns:
        feature: .+
  branches:
    feature:
      steps:
        - test:
          - work:
          - work:
          - work:
